"""Brand mode: search for pain points and mention products naturally."""

from __future__ import annotations

from xpersonas.agent.state import AgentState
from xpersonas.platforms.base import PlatformAdapter
from xpersonas.storage.database import Database
from xpersonas.storage.repositories.product_repo import ProductRepo
from xpersonas.storage.repositories.activity_repo import ActivityRepo


async def promo_engage(state: AgentState, config=None) -> dict:
    """Search for pain points and generate product mentions."""
    adapter: PlatformAdapter = config["configurable"]["adapter"]
    db: Database = config["configurable"]["db"]
    persona_id = state.get("persona_id", "")
    persona = state.get("persona_config", {})
    promo_config = persona.get("promo", {})

    if not promo_config.get("enabled"):
        return {}

    product_ids = promo_config.get("product_ids", [])
    if not product_ids:
        return {}

    product_repo = ProductRepo(db)
    activity_repo = ActivityRepo(db)

    # Check weekly frequency cap
    from datetime import datetime, timezone, timedelta
    week_ago = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
    week_row = db.fetchone(
        "SELECT COUNT(*) as cnt FROM activity_log "
        "WHERE persona_id = ? AND is_promo = 1 AND success = 1 "
        "AND timestamp > ?",
        (persona_id, week_ago),
    )
    weekly_count = week_row["cnt"] if week_row else 0
    cap = promo_config.get("frequency_cap_per_week", 3)
    if weekly_count >= cap:
        return {}

    # Load active products
    products = [product_repo.get(pid) for pid in product_ids]
    products = [p for p in products if p and p["is_active"]]
    if not products:
        return {}

    search_queries = promo_config.get("search_queries", [])
    if not search_queries:
        return {}

    pending = list(state.get("pending_actions", []))
    engaged = set(state.get("engaged_ids", []))

    for query in search_queries[:2]:
        try:
            posts = await adapter.search(query, limit=5)
        except Exception:
            continue

        for post in posts:
            if post.id in engaged:
                continue

            post_text = post.text.lower()
            for product in products:
                pain_points = product.get("pain_points", [])
                matched = any(pp.lower() in post_text for pp in pain_points)
                if not matched:
                    continue

                # Check cooldown: already mentioned this product recently?
                three_days_ago = (datetime.now(timezone.utc) - timedelta(days=3)).isoformat()
                recent = db.fetchone(
                    "SELECT id FROM activity_log "
                    "WHERE persona_id = ? AND product_id = ? AND success = 1 "
                    "AND timestamp > ?",
                    (persona_id, product["id"], three_days_ago),
                )
                if recent:
                    continue

                pending.append({
                    "action_type": "reply",
                    "target_id": post.id,
                    "target_author": post.author_handle,
                    "content": None,  # generated by generate_content node
                    "score": 7.5,
                    "reason": f"Natural product mention: {product['name']}",
                    "is_promo": True,
                    "product_id": product["id"],
                })
                break  # one promo per post

    if any(a.get("is_promo") for a in pending):
        return {"pending_actions": pending, "_routing_target": "generate_content"}
    return {"pending_actions": pending}
